/* 
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using harmony-connect-client.Api;
using harmony-connect-client.Model;
using harmony-connect-client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace harmony-connect-client.Test
{
    /// <summary>
    ///  Class for testing AllInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AllInfoTests
    {
        // TODO uncomment below to declare an instance variable for AllInfo
        //private AllInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AllInfo
            //instance = new AllInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AllInfo
        /// </summary>
        [Test]
        public void AllInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AllInfo
            //Assert.IsInstanceOfType<AllInfo> (instance, "variable 'instance' is a AllInfo");
        }


        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

    }

}
