/* 
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using harmony-connect-client.Api;
using harmony-connect-client.Model;
using harmony-connect-client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace harmony-connect-client.Test
{
    /// <summary>
    ///  Class for testing ChainListData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChainListDataTests
    {
        // TODO uncomment below to declare an instance variable for ChainListData
        //private ChainListData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChainListData
            //instance = new ChainListData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChainListData
        /// </summary>
        [Test]
        public void ChainListDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChainListData
            //Assert.IsInstanceOfType<ChainListData> (instance, "variable 'instance' is a ChainListData");
        }


        /// <summary>
        /// Test the property 'ChainId'
        /// </summary>
        [Test]
        public void ChainIdTest()
        {
            // TODO unit test for the property 'ChainId'
        }
        /// <summary>
        /// Test the property 'ExternalIds'
        /// </summary>
        [Test]
        public void ExternalIdsTest()
        {
            // TODO unit test for the property 'ExternalIds'
        }
        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }
        /// <summary>
        /// Test the property 'Stage'
        /// </summary>
        [Test]
        public void StageTest()
        {
            // TODO unit test for the property 'Stage'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

    }

}
