/* 
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using harmony-connect-client.Api;
using harmony-connect-client.Model;
using harmony-connect-client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace harmony-connect-client.Test
{
    /// <summary>
    ///  Class for testing CommitLong
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CommitLongTests
    {
        // TODO uncomment below to declare an instance variable for CommitLong
        //private CommitLong instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CommitLong
            //instance = new CommitLong();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CommitLong
        /// </summary>
        [Test]
        public void CommitLongInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CommitLong
            //Assert.IsInstanceOfType<CommitLong> (instance, "variable 'instance' is a CommitLong");
        }


        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Test]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }
        /// <summary>
        /// Test the property 'TxId'
        /// </summary>
        [Test]
        public void TxIdTest()
        {
            // TODO unit test for the property 'TxId'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'ChainId'
        /// </summary>
        [Test]
        public void ChainIdTest()
        {
            // TODO unit test for the property 'ChainId'
        }
        /// <summary>
        /// Test the property 'Weld'
        /// </summary>
        [Test]
        public void WeldTest()
        {
            // TODO unit test for the property 'Weld'
        }
        /// <summary>
        /// Test the property 'EntryHash'
        /// </summary>
        [Test]
        public void EntryHashTest()
        {
            // TODO unit test for the property 'EntryHash'
        }
        /// <summary>
        /// Test the property 'EntryCredits'
        /// </summary>
        [Test]
        public void EntryCreditsTest()
        {
            // TODO unit test for the property 'EntryCredits'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Signature'
        /// </summary>
        [Test]
        public void SignatureTest()
        {
            // TODO unit test for the property 'Signature'
        }
        /// <summary>
        /// Test the property 'EcBlock'
        /// </summary>
        [Test]
        public void EcBlockTest()
        {
            // TODO unit test for the property 'EcBlock'
        }

    }

}
