/* 
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using harmony-connect-client.Api;
using harmony-connect-client.Model;
using harmony-connect-client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace harmony-connect-client.Test
{
    /// <summary>
    ///  Class for testing DBlockLongEcblock
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DBlockLongEcblockTests
    {
        // TODO uncomment below to declare an instance variable for DBlockLongEcblock
        //private DBlockLongEcblock instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DBlockLongEcblock
            //instance = new DBlockLongEcblock();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DBlockLongEcblock
        /// </summary>
        [Test]
        public void DBlockLongEcblockInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DBlockLongEcblock
            //Assert.IsInstanceOfType<DBlockLongEcblock> (instance, "variable 'instance' is a DBlockLongEcblock");
        }


        /// <summary>
        /// Test the property 'Keymr'
        /// </summary>
        [Test]
        public void KeymrTest()
        {
            // TODO unit test for the property 'Keymr'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Test]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }

    }

}
