/* 
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using harmony-connect-client.Api;
using harmony-connect-client.Model;
using harmony-connect-client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace harmony-connect-client.Test
{
    /// <summary>
    ///  Class for testing EntryCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EntryCreateTests
    {
        // TODO uncomment below to declare an instance variable for EntryCreate
        //private EntryCreate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EntryCreate
            //instance = new EntryCreate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EntryCreate
        /// </summary>
        [Test]
        public void EntryCreateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EntryCreate
            //Assert.IsInstanceOfType<EntryCreate> (instance, "variable 'instance' is a EntryCreate");
        }


        /// <summary>
        /// Test the property 'ExternalIds'
        /// </summary>
        [Test]
        public void ExternalIdsTest()
        {
            // TODO unit test for the property 'ExternalIds'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'CallbackUrl'
        /// </summary>
        [Test]
        public void CallbackUrlTest()
        {
            // TODO unit test for the property 'CallbackUrl'
        }
        /// <summary>
        /// Test the property 'CallbackStages'
        /// </summary>
        [Test]
        public void CallbackStagesTest()
        {
            // TODO unit test for the property 'CallbackStages'
        }

    }

}
