/* 
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using harmony-connect-client.Api;
using harmony-connect-client.Model;
using harmony-connect-client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace harmony-connect-client.Test
{
    /// <summary>
    ///  Class for testing EntryShort
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EntryShortTests
    {
        // TODO uncomment below to declare an instance variable for EntryShort
        //private EntryShort instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EntryShort
            //instance = new EntryShort();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EntryShort
        /// </summary>
        [Test]
        public void EntryShortInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EntryShort
            //Assert.IsInstanceOfType<EntryShort> (instance, "variable 'instance' is a EntryShort");
        }


        /// <summary>
        /// Test the property 'EntryHash'
        /// </summary>
        [Test]
        public void EntryHashTest()
        {
            // TODO unit test for the property 'EntryHash'
        }
        /// <summary>
        /// Test the property 'Stage'
        /// </summary>
        [Test]
        public void StageTest()
        {
            // TODO unit test for the property 'Stage'
        }

    }

}
