/* 
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using harmony-connect-client.Api;
using harmony-connect-client.Model;
using harmony-connect-client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace harmony-connect-client.Test
{
    /// <summary>
    ///  Class for testing FactomAnchor
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FactomAnchorTests
    {
        // TODO uncomment below to declare an instance variable for FactomAnchor
        //private FactomAnchor instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FactomAnchor
            //instance = new FactomAnchor();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FactomAnchor
        /// </summary>
        [Test]
        public void FactomAnchorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FactomAnchor
            //Assert.IsInstanceOfType<FactomAnchor> (instance, "variable 'instance' is a FactomAnchor");
        }


        /// <summary>
        /// Test the property 'Network'
        /// </summary>
        [Test]
        public void NetworkTest()
        {
            // TODO unit test for the property 'Network'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'EntrySerialized'
        /// </summary>
        [Test]
        public void EntrySerializedTest()
        {
            // TODO unit test for the property 'EntrySerialized'
        }
        /// <summary>
        /// Test the property 'EntryHash'
        /// </summary>
        [Test]
        public void EntryHashTest()
        {
            // TODO unit test for the property 'EntryHash'
        }
        /// <summary>
        /// Test the property 'Dblock'
        /// </summary>
        [Test]
        public void DblockTest()
        {
            // TODO unit test for the property 'Dblock'
        }
        /// <summary>
        /// Test the property 'MerkleBranch'
        /// </summary>
        [Test]
        public void MerkleBranchTest()
        {
            // TODO unit test for the property 'MerkleBranch'
        }

    }

}
