/* 
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using harmony-connect-client.Api;
using harmony-connect-client.Model;
using harmony-connect-client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace harmony-connect-client.Test
{
    /// <summary>
    ///  Class for testing FBlockLong
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FBlockLongTests
    {
        // TODO uncomment below to declare an instance variable for FBlockLong
        //private FBlockLong instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FBlockLong
            //instance = new FBlockLong();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FBlockLong
        /// </summary>
        [Test]
        public void FBlockLongInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FBlockLong
            //Assert.IsInstanceOfType<FBlockLong> (instance, "variable 'instance' is a FBlockLong");
        }


        /// <summary>
        /// Test the property 'Keymr'
        /// </summary>
        [Test]
        public void KeymrTest()
        {
            // TODO unit test for the property 'Keymr'
        }
        /// <summary>
        /// Test the property 'Prev'
        /// </summary>
        [Test]
        public void PrevTest()
        {
            // TODO unit test for the property 'Prev'
        }
        /// <summary>
        /// Test the property 'Next'
        /// </summary>
        [Test]
        public void NextTest()
        {
            // TODO unit test for the property 'Next'
        }
        /// <summary>
        /// Test the property 'Dblock'
        /// </summary>
        [Test]
        public void DblockTest()
        {
            // TODO unit test for the property 'Dblock'
        }
        /// <summary>
        /// Test the property 'EcRate'
        /// </summary>
        [Test]
        public void EcRateTest()
        {
            // TODO unit test for the property 'EcRate'
        }
        /// <summary>
        /// Test the property 'FctTotalInputs'
        /// </summary>
        [Test]
        public void FctTotalInputsTest()
        {
            // TODO unit test for the property 'FctTotalInputs'
        }
        /// <summary>
        /// Test the property 'FctTotalOutputs'
        /// </summary>
        [Test]
        public void FctTotalOutputsTest()
        {
            // TODO unit test for the property 'FctTotalOutputs'
        }
        /// <summary>
        /// Test the property 'EcTotalCreated'
        /// </summary>
        [Test]
        public void EcTotalCreatedTest()
        {
            // TODO unit test for the property 'EcTotalCreated'
        }
        /// <summary>
        /// Test the property 'Transactions'
        /// </summary>
        [Test]
        public void TransactionsTest()
        {
            // TODO unit test for the property 'Transactions'
        }

    }

}
