/* 
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using harmony-connect-client.Api;
using harmony-connect-client.Model;
using harmony-connect-client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace harmony-connect-client.Test
{
    /// <summary>
    ///  Class for testing IdentityKeyData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class IdentityKeyDataTests
    {
        // TODO uncomment below to declare an instance variable for IdentityKeyData
        //private IdentityKeyData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of IdentityKeyData
            //instance = new IdentityKeyData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of IdentityKeyData
        /// </summary>
        [Test]
        public void IdentityKeyDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IdentityKeyData
            //Assert.IsInstanceOfType<IdentityKeyData> (instance, "variable 'instance' is a IdentityKeyData");
        }


        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Test]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'ActivatedHeight'
        /// </summary>
        [Test]
        public void ActivatedHeightTest()
        {
            // TODO unit test for the property 'ActivatedHeight'
        }
        /// <summary>
        /// Test the property 'RetiredHeight'
        /// </summary>
        [Test]
        public void RetiredHeightTest()
        {
            // TODO unit test for the property 'RetiredHeight'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Test]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'EntryHash'
        /// </summary>
        [Test]
        public void EntryHashTest()
        {
            // TODO unit test for the property 'EntryHash'
        }

    }

}
