/* 
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using harmony-connect-client.Api;
using harmony-connect-client.Model;
using harmony-connect-client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace harmony-connect-client.Test
{
    /// <summary>
    ///  Class for testing Transaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TransactionTests
    {
        // TODO uncomment below to declare an instance variable for Transaction
        //private Transaction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Transaction
            //instance = new Transaction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Transaction
        /// </summary>
        [Test]
        public void TransactionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Transaction
            //Assert.IsInstanceOfType<Transaction> (instance, "variable 'instance' is a Transaction");
        }


        /// <summary>
        /// Test the property 'TxId'
        /// </summary>
        [Test]
        public void TxIdTest()
        {
            // TODO unit test for the property 'TxId'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'FctTotalInputs'
        /// </summary>
        [Test]
        public void FctTotalInputsTest()
        {
            // TODO unit test for the property 'FctTotalInputs'
        }
        /// <summary>
        /// Test the property 'FctTotalOutputs'
        /// </summary>
        [Test]
        public void FctTotalOutputsTest()
        {
            // TODO unit test for the property 'FctTotalOutputs'
        }
        /// <summary>
        /// Test the property 'EcCreated'
        /// </summary>
        [Test]
        public void EcCreatedTest()
        {
            // TODO unit test for the property 'EcCreated'
        }
        /// <summary>
        /// Test the property 'EcRate'
        /// </summary>
        [Test]
        public void EcRateTest()
        {
            // TODO unit test for the property 'EcRate'
        }
        /// <summary>
        /// Test the property 'FctFee'
        /// </summary>
        [Test]
        public void FctFeeTest()
        {
            // TODO unit test for the property 'FctFee'
        }
        /// <summary>
        /// Test the property 'Dblock'
        /// </summary>
        [Test]
        public void DblockTest()
        {
            // TODO unit test for the property 'Dblock'
        }
        /// <summary>
        /// Test the property 'Fblock'
        /// </summary>
        [Test]
        public void FblockTest()
        {
            // TODO unit test for the property 'Fblock'
        }
        /// <summary>
        /// Test the property 'Inputs'
        /// </summary>
        [Test]
        public void InputsTest()
        {
            // TODO unit test for the property 'Inputs'
        }
        /// <summary>
        /// Test the property 'Outputs'
        /// </summary>
        [Test]
        public void OutputsTest()
        {
            // TODO unit test for the property 'Outputs'
        }

    }

}
