/* 
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using harmony-connect-client.Api;
using harmony-connect-client.Model;
using harmony-connect-client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace harmony-connect-client.Test
{
    /// <summary>
    ///  Class for testing TransactionLinkShort
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TransactionLinkShortTests
    {
        // TODO uncomment below to declare an instance variable for TransactionLinkShort
        //private TransactionLinkShort instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransactionLinkShort
            //instance = new TransactionLinkShort();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransactionLinkShort
        /// </summary>
        [Test]
        public void TransactionLinkShortInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TransactionLinkShort
            //Assert.IsInstanceOfType<TransactionLinkShort> (instance, "variable 'instance' is a TransactionLinkShort");
        }


        /// <summary>
        /// Test the property 'TxId'
        /// </summary>
        [Test]
        public void TxIdTest()
        {
            // TODO unit test for the property 'TxId'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }
        /// <summary>
        /// Test the property 'EcRate'
        /// </summary>
        [Test]
        public void EcRateTest()
        {
            // TODO unit test for the property 'EcRate'
        }

    }

}
