/* 
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using harmony-connect-client.Client;
using harmony-connect-client.Model;

namespace harmony-connect-client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IInfoApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// API Info
        /// </summary>
        /// <remarks>
        /// Request general information about the Connect API such as the version and available endpoints.
        /// </remarks>
        /// <exception cref="harmony-connect-client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>AllInfo</returns>
        AllInfo GetApiInfo ();

        /// <summary>
        /// API Info
        /// </summary>
        /// <remarks>
        /// Request general information about the Connect API such as the version and available endpoints.
        /// </remarks>
        /// <exception cref="harmony-connect-client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of AllInfo</returns>
        ApiResponse<AllInfo> GetApiInfoWithHttpInfo ();
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// API Info
        /// </summary>
        /// <remarks>
        /// Request general information about the Connect API such as the version and available endpoints.
        /// </remarks>
        /// <exception cref="harmony-connect-client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of AllInfo</returns>
        System.Threading.Tasks.Task<AllInfo> GetApiInfoAsync ();

        /// <summary>
        /// API Info
        /// </summary>
        /// <remarks>
        /// Request general information about the Connect API such as the version and available endpoints.
        /// </remarks>
        /// <exception cref="harmony-connect-client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (AllInfo)</returns>
        System.Threading.Tasks.Task<ApiResponse<AllInfo>> GetApiInfoAsyncWithHttpInfo ();
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class InfoApi : IInfoApi
    {
        private harmony-connect-client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="InfoApi"/> class.
        /// </summary>
        /// <returns></returns>
        public InfoApi(String basePath)
        {
            this.Configuration = new harmony-connect-client.Client.Configuration { BasePath = basePath };

            ExceptionFactory = harmony-connect-client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InfoApi"/> class
        /// </summary>
        /// <returns></returns>
        public InfoApi()
        {
            this.Configuration = harmony-connect-client.Client.Configuration.Default;

            ExceptionFactory = harmony-connect-client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InfoApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public InfoApi(harmony-connect-client.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = harmony-connect-client.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = harmony-connect-client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public harmony-connect-client.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public harmony-connect-client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// API Info Request general information about the Connect API such as the version and available endpoints.
        /// </summary>
        /// <exception cref="harmony-connect-client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>AllInfo</returns>
        public AllInfo GetApiInfo ()
        {
             ApiResponse<AllInfo> localVarResponse = GetApiInfoWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// API Info Request general information about the Connect API such as the version and available endpoints.
        /// </summary>
        /// <exception cref="harmony-connect-client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of AllInfo</returns>
        public ApiResponse< AllInfo > GetApiInfoWithHttpInfo ()
        {

            var localVarPath = "/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (AppId) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("app_id")))
            {
                localVarHeaderParams["app_id"] = this.Configuration.GetApiKeyWithPrefix("app_id");
            }
            // authentication (AppKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("app_key")))
            {
                localVarHeaderParams["app_key"] = this.Configuration.GetApiKeyWithPrefix("app_key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetApiInfo", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AllInfo>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AllInfo) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AllInfo)));
        }

        /// <summary>
        /// API Info Request general information about the Connect API such as the version and available endpoints.
        /// </summary>
        /// <exception cref="harmony-connect-client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of AllInfo</returns>
        public async System.Threading.Tasks.Task<AllInfo> GetApiInfoAsync ()
        {
             ApiResponse<AllInfo> localVarResponse = await GetApiInfoAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// API Info Request general information about the Connect API such as the version and available endpoints.
        /// </summary>
        /// <exception cref="harmony-connect-client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (AllInfo)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AllInfo>> GetApiInfoAsyncWithHttpInfo ()
        {

            var localVarPath = "/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // authentication (AppId) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("app_id")))
            {
                localVarHeaderParams["app_id"] = this.Configuration.GetApiKeyWithPrefix("app_id");
            }
            // authentication (AppKey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("app_key")))
            {
                localVarHeaderParams["app_key"] = this.Configuration.GetApiKeyWithPrefix("app_key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetApiInfo", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AllInfo>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AllInfo) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AllInfo)));
        }

    }
}
