/* 
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = harmony-connect-client.Client.OpenAPIDateConverter;

namespace harmony-connect-client.Model
{
    /// <summary>
    /// Contains information about the desired Directory Block Anchor.
    /// </summary>
    [DataContract]
    public partial class AnchorLongData :  IEquatable<AnchorLongData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AnchorLongData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AnchorLongData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AnchorLongData" /> class.
        /// </summary>
        /// <param name="dblock">dblock (required).</param>
        /// <param name="anchors">A list of all the anchors of this Directory Block. (required).</param>
        public AnchorLongData(DBlockLink dblock = default(DBlockLink), List<SingleAnchor> anchors = default(List<SingleAnchor>))
        {
            // to ensure "dblock" is required (not null)
            if (dblock == null)
            {
                throw new InvalidDataException("dblock is a required property for AnchorLongData and cannot be null");
            }
            else
            {
                this.Dblock = dblock;
            }
            // to ensure "anchors" is required (not null)
            if (anchors == null)
            {
                throw new InvalidDataException("anchors is a required property for AnchorLongData and cannot be null");
            }
            else
            {
                this.Anchors = anchors;
            }
        }
        
        /// <summary>
        /// Gets or Sets Dblock
        /// </summary>
        [DataMember(Name="dblock", EmitDefaultValue=false)]
        public DBlockLink Dblock { get; set; }

        /// <summary>
        /// A list of all the anchors of this Directory Block.
        /// </summary>
        /// <value>A list of all the anchors of this Directory Block.</value>
        [DataMember(Name="anchors", EmitDefaultValue=false)]
        public List<SingleAnchor> Anchors { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AnchorLongData {\n");
            sb.Append("  Dblock: ").Append(Dblock).Append("\n");
            sb.Append("  Anchors: ").Append(Anchors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AnchorLongData);
        }

        /// <summary>
        /// Returns true if AnchorLongData instances are equal
        /// </summary>
        /// <param name="input">Instance of AnchorLongData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AnchorLongData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Dblock == input.Dblock ||
                    (this.Dblock != null &&
                    this.Dblock.Equals(input.Dblock))
                ) && 
                (
                    this.Anchors == input.Anchors ||
                    this.Anchors != null &&
                    this.Anchors.SequenceEqual(input.Anchors)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Dblock != null)
                    hashCode = hashCode * 59 + this.Dblock.GetHashCode();
                if (this.Anchors != null)
                    hashCode = hashCode * 59 + this.Anchors.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
