/* 
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = harmony-connect-client.Client.OpenAPIDateConverter;

namespace harmony-connect-client.Model
{
    /// <summary>
    /// Represents a list of Factom chains that have been or will be saved to the blockchain.
    /// </summary>
    [DataContract]
    public partial class ChainShort :  IEquatable<ChainShort>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChainShort" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ChainShort() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ChainShort" /> class.
        /// </summary>
        /// <param name="chainId">This is the unique identifier created for each chain. (required).</param>
        /// <param name="entryHash">The unique identifier of the chain&#39;s first entry. (required).</param>
        /// <param name="stage">The immutability stage that this chain has reached. (required).</param>
        public ChainShort(string chainId = default(string), string entryHash = default(string), string stage = default(string))
        {
            // to ensure "chainId" is required (not null)
            if (chainId == null)
            {
                throw new InvalidDataException("chainId is a required property for ChainShort and cannot be null");
            }
            else
            {
                this.ChainId = chainId;
            }
            // to ensure "entryHash" is required (not null)
            if (entryHash == null)
            {
                throw new InvalidDataException("entryHash is a required property for ChainShort and cannot be null");
            }
            else
            {
                this.EntryHash = entryHash;
            }
            // to ensure "stage" is required (not null)
            if (stage == null)
            {
                throw new InvalidDataException("stage is a required property for ChainShort and cannot be null");
            }
            else
            {
                this.Stage = stage;
            }
        }
        
        /// <summary>
        /// This is the unique identifier created for each chain.
        /// </summary>
        /// <value>This is the unique identifier created for each chain.</value>
        [DataMember(Name="chain_id", EmitDefaultValue=false)]
        public string ChainId { get; set; }

        /// <summary>
        /// The unique identifier of the chain&#39;s first entry.
        /// </summary>
        /// <value>The unique identifier of the chain&#39;s first entry.</value>
        [DataMember(Name="entry_hash", EmitDefaultValue=false)]
        public string EntryHash { get; set; }

        /// <summary>
        /// The immutability stage that this chain has reached.
        /// </summary>
        /// <value>The immutability stage that this chain has reached.</value>
        [DataMember(Name="stage", EmitDefaultValue=false)]
        public string Stage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ChainShort {\n");
            sb.Append("  ChainId: ").Append(ChainId).Append("\n");
            sb.Append("  EntryHash: ").Append(EntryHash).Append("\n");
            sb.Append("  Stage: ").Append(Stage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ChainShort);
        }

        /// <summary>
        /// Returns true if ChainShort instances are equal
        /// </summary>
        /// <param name="input">Instance of ChainShort to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ChainShort input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ChainId == input.ChainId ||
                    (this.ChainId != null &&
                    this.ChainId.Equals(input.ChainId))
                ) && 
                (
                    this.EntryHash == input.EntryHash ||
                    (this.EntryHash != null &&
                    this.EntryHash.Equals(input.EntryHash))
                ) && 
                (
                    this.Stage == input.Stage ||
                    (this.Stage != null &&
                    this.Stage.Equals(input.Stage))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ChainId != null)
                    hashCode = hashCode * 59 + this.ChainId.GetHashCode();
                if (this.EntryHash != null)
                    hashCode = hashCode * 59 + this.EntryHash.GetHashCode();
                if (this.Stage != null)
                    hashCode = hashCode * 59 + this.Stage.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
