/* 
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = harmony-connect-client.Client.OpenAPIDateConverter;

namespace harmony-connect-client.Model
{
    /// <summary>
    /// EntrySearchResponseData
    /// </summary>
    [DataContract]
    public partial class EntrySearchResponseData :  IEquatable<EntrySearchResponseData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EntrySearchResponseData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EntrySearchResponseData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EntrySearchResponseData" /> class.
        /// </summary>
        /// <param name="entryHash">The unique identitfier of the entry. (required).</param>
        /// <param name="externalIds">Tags that can be used to identify this entry. (required).</param>
        /// <param name="stage">The level of immutability that this entry has reached. (required).</param>
        /// <param name="href">An API link to retrieve all information about this entry. (required).</param>
        public EntrySearchResponseData(string entryHash = default(string), List<string> externalIds = default(List<string>), string stage = default(string), string href = default(string))
        {
            // to ensure "entryHash" is required (not null)
            if (entryHash == null)
            {
                throw new InvalidDataException("entryHash is a required property for EntrySearchResponseData and cannot be null");
            }
            else
            {
                this.EntryHash = entryHash;
            }
            // to ensure "externalIds" is required (not null)
            if (externalIds == null)
            {
                throw new InvalidDataException("externalIds is a required property for EntrySearchResponseData and cannot be null");
            }
            else
            {
                this.ExternalIds = externalIds;
            }
            // to ensure "stage" is required (not null)
            if (stage == null)
            {
                throw new InvalidDataException("stage is a required property for EntrySearchResponseData and cannot be null");
            }
            else
            {
                this.Stage = stage;
            }
            // to ensure "href" is required (not null)
            if (href == null)
            {
                throw new InvalidDataException("href is a required property for EntrySearchResponseData and cannot be null");
            }
            else
            {
                this.Href = href;
            }
        }
        
        /// <summary>
        /// The unique identitfier of the entry.
        /// </summary>
        /// <value>The unique identitfier of the entry.</value>
        [DataMember(Name="entry_hash", EmitDefaultValue=false)]
        public string EntryHash { get; set; }

        /// <summary>
        /// Tags that can be used to identify this entry.
        /// </summary>
        /// <value>Tags that can be used to identify this entry.</value>
        [DataMember(Name="external_ids", EmitDefaultValue=false)]
        public List<string> ExternalIds { get; set; }

        /// <summary>
        /// The level of immutability that this entry has reached.
        /// </summary>
        /// <value>The level of immutability that this entry has reached.</value>
        [DataMember(Name="stage", EmitDefaultValue=false)]
        public string Stage { get; set; }

        /// <summary>
        /// An API link to retrieve all information about this entry.
        /// </summary>
        /// <value>An API link to retrieve all information about this entry.</value>
        [DataMember(Name="href", EmitDefaultValue=false)]
        public string Href { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EntrySearchResponseData {\n");
            sb.Append("  EntryHash: ").Append(EntryHash).Append("\n");
            sb.Append("  ExternalIds: ").Append(ExternalIds).Append("\n");
            sb.Append("  Stage: ").Append(Stage).Append("\n");
            sb.Append("  Href: ").Append(Href).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EntrySearchResponseData);
        }

        /// <summary>
        /// Returns true if EntrySearchResponseData instances are equal
        /// </summary>
        /// <param name="input">Instance of EntrySearchResponseData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EntrySearchResponseData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.EntryHash == input.EntryHash ||
                    (this.EntryHash != null &&
                    this.EntryHash.Equals(input.EntryHash))
                ) && 
                (
                    this.ExternalIds == input.ExternalIds ||
                    this.ExternalIds != null &&
                    this.ExternalIds.SequenceEqual(input.ExternalIds)
                ) && 
                (
                    this.Stage == input.Stage ||
                    (this.Stage != null &&
                    this.Stage.Equals(input.Stage))
                ) && 
                (
                    this.Href == input.Href ||
                    (this.Href != null &&
                    this.Href.Equals(input.Href))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EntryHash != null)
                    hashCode = hashCode * 59 + this.EntryHash.GetHashCode();
                if (this.ExternalIds != null)
                    hashCode = hashCode * 59 + this.ExternalIds.GetHashCode();
                if (this.Stage != null)
                    hashCode = hashCode * 59 + this.Stage.GetHashCode();
                if (this.Href != null)
                    hashCode = hashCode * 59 + this.Href.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
