/* 
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = harmony-connect-client.Client.OpenAPIDateConverter;

namespace harmony-connect-client.Model
{
    /// <summary>
    /// FactomAnchor
    /// </summary>
    [DataContract]
    public partial class FactomAnchor :  IEquatable<FactomAnchor>, IValidatableObject
    {
        /// <summary>
        /// Indicates the blockchain network that contains this anchor.
        /// </summary>
        /// <value>Indicates the blockchain network that contains this anchor.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum NetworkEnum
        {
            /// <summary>
            /// Enum Bitcoin for value: bitcoin
            /// </summary>
            [EnumMember(Value = "bitcoin")]
            Bitcoin = 1,

            /// <summary>
            /// Enum Ethereum for value: ethereum
            /// </summary>
            [EnumMember(Value = "ethereum")]
            Ethereum = 2,

            /// <summary>
            /// Enum Factom for value: factom
            /// </summary>
            [EnumMember(Value = "factom")]
            Factom = 3

        }

        /// <summary>
        /// Indicates the blockchain network that contains this anchor.
        /// </summary>
        /// <value>Indicates the blockchain network that contains this anchor.</value>
        [DataMember(Name="network", EmitDefaultValue=false)]
        public NetworkEnum Network { get; set; }
        /// <summary>
        /// The confirmation status of the anchor. Either pending or confirmed.
        /// </summary>
        /// <value>The confirmation status of the anchor. Either pending or confirmed.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Pending for value: pending
            /// </summary>
            [EnumMember(Value = "pending")]
            Pending = 1,

            /// <summary>
            /// Enum Confirmed for value: confirmed
            /// </summary>
            [EnumMember(Value = "confirmed")]
            Confirmed = 2

        }

        /// <summary>
        /// The confirmation status of the anchor. Either pending or confirmed.
        /// </summary>
        /// <value>The confirmation status of the anchor. Either pending or confirmed.</value>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="FactomAnchor" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FactomAnchor() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FactomAnchor" /> class.
        /// </summary>
        /// <param name="network">Indicates the blockchain network that contains this anchor. (required).</param>
        /// <param name="status">The confirmation status of the anchor. Either pending or confirmed. (required).</param>
        /// <param name="createdAt">The time at which this entry was created. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: &#x60;YYYY-MM-DDThh:mm:ss.ssssssZ&#x60; This will be null if the chain is not at least at the &#x60;factom&#x60; immutability stage..</param>
        /// <param name="entrySerialized">The raw data that makes up the entry..</param>
        /// <param name="entryHash">The unique identitfier of the entry..</param>
        /// <param name="dblock">dblock.</param>
        /// <param name="merkleBranch">The branch of the merkle tree that represents this anchor. Presented as an array of Merkle nodes..</param>
        public FactomAnchor(NetworkEnum network = default(NetworkEnum), StatusEnum status = default(StatusEnum), string createdAt = default(string), string entrySerialized = default(string), string entryHash = default(string), DBlockLink dblock = default(DBlockLink), List<MerkleNode> merkleBranch = default(List<MerkleNode>))
        {
            // to ensure "network" is required (not null)
            if (network == null)
            {
                throw new InvalidDataException("network is a required property for FactomAnchor and cannot be null");
            }
            else
            {
                this.Network = network;
            }
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new InvalidDataException("status is a required property for FactomAnchor and cannot be null");
            }
            else
            {
                this.Status = status;
            }
            this.CreatedAt = createdAt;
            this.EntrySerialized = entrySerialized;
            this.EntryHash = entryHash;
            this.Dblock = dblock;
            this.MerkleBranch = merkleBranch;
        }
        


        /// <summary>
        /// The time at which this entry was created. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: &#x60;YYYY-MM-DDThh:mm:ss.ssssssZ&#x60; This will be null if the chain is not at least at the &#x60;factom&#x60; immutability stage.
        /// </summary>
        /// <value>The time at which this entry was created. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: &#x60;YYYY-MM-DDThh:mm:ss.ssssssZ&#x60; This will be null if the chain is not at least at the &#x60;factom&#x60; immutability stage.</value>
        [DataMember(Name="created_at", EmitDefaultValue=false)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// The raw data that makes up the entry.
        /// </summary>
        /// <value>The raw data that makes up the entry.</value>
        [DataMember(Name="entry_serialized", EmitDefaultValue=false)]
        public string EntrySerialized { get; set; }

        /// <summary>
        /// The unique identitfier of the entry.
        /// </summary>
        /// <value>The unique identitfier of the entry.</value>
        [DataMember(Name="entry_hash", EmitDefaultValue=false)]
        public string EntryHash { get; set; }

        /// <summary>
        /// Gets or Sets Dblock
        /// </summary>
        [DataMember(Name="dblock", EmitDefaultValue=false)]
        public DBlockLink Dblock { get; set; }

        /// <summary>
        /// The branch of the merkle tree that represents this anchor. Presented as an array of Merkle nodes.
        /// </summary>
        /// <value>The branch of the merkle tree that represents this anchor. Presented as an array of Merkle nodes.</value>
        [DataMember(Name="merkle_branch", EmitDefaultValue=false)]
        public List<MerkleNode> MerkleBranch { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FactomAnchor {\n");
            sb.Append("  Network: ").Append(Network).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  EntrySerialized: ").Append(EntrySerialized).Append("\n");
            sb.Append("  EntryHash: ").Append(EntryHash).Append("\n");
            sb.Append("  Dblock: ").Append(Dblock).Append("\n");
            sb.Append("  MerkleBranch: ").Append(MerkleBranch).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FactomAnchor);
        }

        /// <summary>
        /// Returns true if FactomAnchor instances are equal
        /// </summary>
        /// <param name="input">Instance of FactomAnchor to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FactomAnchor input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Network == input.Network ||
                    (this.Network != null &&
                    this.Network.Equals(input.Network))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.CreatedAt == input.CreatedAt ||
                    (this.CreatedAt != null &&
                    this.CreatedAt.Equals(input.CreatedAt))
                ) && 
                (
                    this.EntrySerialized == input.EntrySerialized ||
                    (this.EntrySerialized != null &&
                    this.EntrySerialized.Equals(input.EntrySerialized))
                ) && 
                (
                    this.EntryHash == input.EntryHash ||
                    (this.EntryHash != null &&
                    this.EntryHash.Equals(input.EntryHash))
                ) && 
                (
                    this.Dblock == input.Dblock ||
                    (this.Dblock != null &&
                    this.Dblock.Equals(input.Dblock))
                ) && 
                (
                    this.MerkleBranch == input.MerkleBranch ||
                    this.MerkleBranch != null &&
                    this.MerkleBranch.SequenceEqual(input.MerkleBranch)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Network != null)
                    hashCode = hashCode * 59 + this.Network.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.CreatedAt != null)
                    hashCode = hashCode * 59 + this.CreatedAt.GetHashCode();
                if (this.EntrySerialized != null)
                    hashCode = hashCode * 59 + this.EntrySerialized.GetHashCode();
                if (this.EntryHash != null)
                    hashCode = hashCode * 59 + this.EntryHash.GetHashCode();
                if (this.Dblock != null)
                    hashCode = hashCode * 59 + this.Dblock.GetHashCode();
                if (this.MerkleBranch != null)
                    hashCode = hashCode * 59 + this.MerkleBranch.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
