/* 
 * Harmony Connect
 *
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.19
 * Contact: harmony-support@factom.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = harmony-connect-client.Client.OpenAPIDateConverter;

namespace harmony-connect-client.Model
{
    /// <summary>
    /// A single factoid block from the factom blockchain.
    /// </summary>
    [DataContract]
    public partial class FBlockShort :  IEquatable<FBlockShort>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FBlockShort" /> class.
        /// </summary>
        /// <param name="keymr">The SHA256 Hash of this entry..</param>
        /// <param name="href">An API link to obtain the full set of data for this factoid block..</param>
        /// <param name="dblock">dblock.</param>
        /// <param name="ecRate">The Entry credit rate at the time this block was created..</param>
        /// <param name="transactions">The number of factoid transactions that occur in this block..</param>
        public FBlockShort(string keymr = default(string), string href = default(string), ABlockLongDblock dblock = default(ABlockLongDblock), string ecRate = default(string), string transactions = default(string))
        {
            this.Keymr = keymr;
            this.Href = href;
            this.Dblock = dblock;
            this.EcRate = ecRate;
            this.Transactions = transactions;
        }
        
        /// <summary>
        /// The SHA256 Hash of this entry.
        /// </summary>
        /// <value>The SHA256 Hash of this entry.</value>
        [DataMember(Name="keymr", EmitDefaultValue=false)]
        public string Keymr { get; set; }

        /// <summary>
        /// An API link to obtain the full set of data for this factoid block.
        /// </summary>
        /// <value>An API link to obtain the full set of data for this factoid block.</value>
        [DataMember(Name="href", EmitDefaultValue=false)]
        public string Href { get; set; }

        /// <summary>
        /// Gets or Sets Dblock
        /// </summary>
        [DataMember(Name="dblock", EmitDefaultValue=false)]
        public ABlockLongDblock Dblock { get; set; }

        /// <summary>
        /// The Entry credit rate at the time this block was created.
        /// </summary>
        /// <value>The Entry credit rate at the time this block was created.</value>
        [DataMember(Name="ec_rate", EmitDefaultValue=false)]
        public string EcRate { get; set; }

        /// <summary>
        /// The number of factoid transactions that occur in this block.
        /// </summary>
        /// <value>The number of factoid transactions that occur in this block.</value>
        [DataMember(Name="transactions", EmitDefaultValue=false)]
        public string Transactions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FBlockShort {\n");
            sb.Append("  Keymr: ").Append(Keymr).Append("\n");
            sb.Append("  Href: ").Append(Href).Append("\n");
            sb.Append("  Dblock: ").Append(Dblock).Append("\n");
            sb.Append("  EcRate: ").Append(EcRate).Append("\n");
            sb.Append("  Transactions: ").Append(Transactions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FBlockShort);
        }

        /// <summary>
        /// Returns true if FBlockShort instances are equal
        /// </summary>
        /// <param name="input">Instance of FBlockShort to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FBlockShort input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Keymr == input.Keymr ||
                    (this.Keymr != null &&
                    this.Keymr.Equals(input.Keymr))
                ) && 
                (
                    this.Href == input.Href ||
                    (this.Href != null &&
                    this.Href.Equals(input.Href))
                ) && 
                (
                    this.Dblock == input.Dblock ||
                    (this.Dblock != null &&
                    this.Dblock.Equals(input.Dblock))
                ) && 
                (
                    this.EcRate == input.EcRate ||
                    (this.EcRate != null &&
                    this.EcRate.Equals(input.EcRate))
                ) && 
                (
                    this.Transactions == input.Transactions ||
                    (this.Transactions != null &&
                    this.Transactions.Equals(input.Transactions))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Keymr != null)
                    hashCode = hashCode * 59 + this.Keymr.GetHashCode();
                if (this.Href != null)
                    hashCode = hashCode * 59 + this.Href.GetHashCode();
                if (this.Dblock != null)
                    hashCode = hashCode * 59 + this.Dblock.GetHashCode();
                if (this.EcRate != null)
                    hashCode = hashCode * 59 + this.EcRate.GetHashCode();
                if (this.Transactions != null)
                    hashCode = hashCode * 59 + this.Transactions.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
